import { SQLDatabase } from "encore.dev/storage/sqldb";

// Define a database named 'encore_prisma_test', using the database migrations
// in the "./prisma/migrations" folder (where prisma will generate their migrations).
// Set `source` to `prisma` to let Encore know that the migrations are generated by Prisma.
export const DB = new SQLDatabase('votev6', {
  migrations: {
    path: './prisma/migrations',
    source: 'prisma',
  },
});